//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.22 at 03:13:00 PM MEZ 
//

package org.adiusframework.processmanager.xml;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.adiusframework.processmanager.xml
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: org.adiusframework.processmanager.xml
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link ServiceProcessType }
	 * 
	 */
	public ServiceProcessType createServiceProcessType() {
		return new ServiceProcessType();
	}

	/**
	 * Create an instance of {@link TaskType }
	 * 
	 */
	public TaskType createTaskType() {
		return new TaskType();
	}

	/**
	 * Create an instance of {@link TasksType }
	 * 
	 */
	public TasksType createTasksType() {
		return new TasksType();
	}

	/**
	 * Create an instance of {@link ProcessDefinition }
	 * 
	 */
	public ProcessDefinition createProcessDefinition() {
		return new ProcessDefinition();
	}

	/**
	 * Create an instance of {@link ServiceTemplateType }
	 * 
	 */
	public ServiceTemplateType createServiceTemplateType() {
		return new ServiceTemplateType();
	}

	/**
	 * Create an instance of {@link ProcessType }
	 * 
	 */
	public ProcessType createProcessType() {
		return new ProcessType();
	}

}
