//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.22 at 03:13:00 PM MEZ 
//

package org.adiusframework.processmanager.xml;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.adiusframework.util.GenericToStringExtender;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.adiusframework.org/processmanager/xml}processType"/>
 *         &lt;element name="tasks" type="{http://www.adiusframework.org/processmanager/xml}tasksType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "type", "tasks" })
@XmlRootElement(name = "processDefinition")
public class ProcessDefinition extends GenericToStringExtender implements Serializable {

	private final static long serialVersionUID = 1L;
	@XmlElement(required = true)
	protected ProcessType type;
	@XmlElement(required = true)
	protected TasksType tasks;

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link ProcessType }
	 * 
	 */
	public ProcessType getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link ProcessType }
	 * 
	 */
	public void setType(ProcessType value) {
		this.type = value;
	}

	/**
	 * Gets the value of the tasks property.
	 * 
	 * @return possible object is {@link TasksType }
	 * 
	 */
	public TasksType getTasks() {
		return tasks;
	}

	/**
	 * Sets the value of the tasks property.
	 * 
	 * @param value
	 *            allowed object is {@link TasksType }
	 * 
	 */
	public void setTasks(TasksType value) {
		this.tasks = value;
	}

}
