//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.22 at 03:13:00 PM MEZ 
//

package org.adiusframework.processmanager.xml;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.adiusframework.util.GenericToStringExtender;

/**
 * <p>
 * Java class for processType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="processType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="aspect" type="{http://www.adiusframework.org/processmanager/xml}aspect" />
 *       &lt;attribute name="domain" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "processType")
public class ProcessType extends GenericToStringExtender implements Serializable {

	private final static long serialVersionUID = 1L;
	@XmlAttribute
	protected String name;
	@XmlAttribute
	protected Aspect aspect;
	@XmlAttribute
	protected String domain;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the aspect property.
	 * 
	 * @return possible object is {@link Aspect }
	 * 
	 */
	public Aspect getAspect() {
		return aspect;
	}

	/**
	 * Sets the value of the aspect property.
	 * 
	 * @param value
	 *            allowed object is {@link Aspect }
	 * 
	 */
	public void setAspect(Aspect value) {
		this.aspect = value;
	}

	/**
	 * Gets the value of the domain property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDomain() {
		return domain;
	}

	/**
	 * Sets the value of the domain property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDomain(String value) {
		this.domain = value;
	}

}
