//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.22 at 03:13:00 PM MEZ 
//

package org.adiusframework.processmanager.xml;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.adiusframework.util.GenericToStringExtender;

/**
 * <p>
 * Java class for taskType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="taskType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="serviceTemplate" type="{http://www.adiusframework.org/processmanager/xml}serviceTemplateType"/>
 *         &lt;element name="serviceProcess" type="{http://www.adiusframework.org/processmanager/xml}serviceProcessType"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "taskType", propOrder = { "serviceTemplate", "serviceProcess" })
public class TaskType extends GenericToStringExtender implements Serializable {

	private final static long serialVersionUID = 1L;
	protected ServiceTemplateType serviceTemplate;
	protected ServiceProcessType serviceProcess;
	@XmlAttribute
	protected String name;

	/**
	 * Gets the value of the serviceTemplate property.
	 * 
	 * @return possible object is {@link ServiceTemplateType }
	 * 
	 */
	public ServiceTemplateType getServiceTemplate() {
		return serviceTemplate;
	}

	/**
	 * Sets the value of the serviceTemplate property.
	 * 
	 * @param value
	 *            allowed object is {@link ServiceTemplateType }
	 * 
	 */
	public void setServiceTemplate(ServiceTemplateType value) {
		this.serviceTemplate = value;
	}

	/**
	 * Gets the value of the serviceProcess property.
	 * 
	 * @return possible object is {@link ServiceProcessType }
	 * 
	 */
	public ServiceProcessType getServiceProcess() {
		return serviceProcess;
	}

	/**
	 * Sets the value of the serviceProcess property.
	 * 
	 * @param value
	 *            allowed object is {@link ServiceProcessType }
	 * 
	 */
	public void setServiceProcess(ServiceProcessType value) {
		this.serviceProcess = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

}
