//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.22 at 03:12:59 PM MEZ 
//

package org.adiusframework.serviceprovider.xml;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.adiusframework.util.GenericToStringExtender;

/**
 * <p>
 * Java class for protocolData complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="protocolData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="jmsData" type="{http://www.adiusframework.org/serviceprovider/xml}jmsData"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "protocolData", propOrder = { "jmsData" })
public class ProtocolData extends GenericToStringExtender implements Serializable {

	private final static long serialVersionUID = 1L;
	protected JmsData jmsData;

	/**
	 * Gets the value of the jmsData property.
	 * 
	 * @return possible object is {@link JmsData }
	 * 
	 */
	public JmsData getJmsData() {
		return jmsData;
	}

	/**
	 * Sets the value of the jmsData property.
	 * 
	 * @param value
	 *            allowed object is {@link JmsData }
	 * 
	 */
	public void setJmsData(JmsData value) {
		this.jmsData = value;
	}

}
