package org.adiusframework.processmanager;

import java.io.Serializable;

import org.adiusframework.service.ServiceResult;

/**
 * This class is used to enable the ServiceProcess-related processing of a
 * ServiceResult which is generated by a service-process.
 */
public interface ServiceResultData extends Serializable {

	/**
	 * Returns the identifier of the ServiceProcess to which the ServiceResult
	 * is associated.
	 * 
	 * @return The identifier.
	 */
	public String getCorrelationId();

	/**
	 * Is used to indicate if an error occurs or the processing was successful.
	 * 
	 * @return True if the processing failed, false otherwise.
	 */
	public boolean failed();

	/**
	 * Returns the "real" ServiceResult how it was generated by the
	 * service-process.
	 * 
	 * @return The related ServiceResult.
	 */
	public ServiceResult getResult();

}
