//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.22 at 03:13:00 PM MEZ 
//

package org.adiusframework.service.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for category.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="category">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="integration"/>
 *     &lt;enumeration value="extraction"/>
 *     &lt;enumeration value="analysis"/>
 *     &lt;enumeration value="generation"/>
 *     &lt;enumeration value="planning"/>
 *     &lt;enumeration value="decomposing"/>
 *     &lt;enumeration value="transformation"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "category")
@XmlEnum
public enum Category {

	@XmlEnumValue("integration")
	INTEGRATION("integration"), @XmlEnumValue("extraction")
	EXTRACTION("extraction"), @XmlEnumValue("analysis")
	ANALYSIS("analysis"), @XmlEnumValue("generation")
	GENERATION("generation"), @XmlEnumValue("planning")
	PLANNING("planning"), @XmlEnumValue("decomposing")
	DECOMPOSING("decomposing"), @XmlEnumValue("transformation")
	TRANSFORMATION("transformation");
	private final String value;

	Category(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static Category fromValue(String v) {
		for (Category c : Category.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
