//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.22 at 03:13:00 PM MEZ 
//

package org.adiusframework.service.xml;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.adiusframework.service.xml package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: org.adiusframework.service.xml
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link ResourceEffectList }
	 * 
	 */
	public ResourceEffectList createResourceEffectList() {
		return new ResourceEffectList();
	}

	/**
	 * Create an instance of {@link ServiceBinding }
	 * 
	 */
	public ServiceBinding createServiceBinding() {
		return new ServiceBinding();
	}

	/**
	 * Create an instance of {@link ServiceDefinition }
	 * 
	 */
	public ServiceDefinition createServiceDefinition() {
		return new ServiceDefinition();
	}

	/**
	 * Create an instance of {@link ServiceCapability }
	 * 
	 */
	public ServiceCapability createServiceCapability() {
		return new ServiceCapability();
	}

	/**
	 * Create an instance of {@link ResourceRequirement }
	 * 
	 */
	public ResourceRequirement createResourceRequirement() {
		return new ResourceRequirement();
	}

	/**
	 * Create an instance of {@link ResourceRequirementList }
	 * 
	 */
	public ResourceRequirementList createResourceRequirementList() {
		return new ResourceRequirementList();
	}

	/**
	 * Create an instance of {@link ResourceEffect }
	 * 
	 */
	public ResourceEffect createResourceEffect() {
		return new ResourceEffect();
	}

	/**
	 * Create an instance of {@link ServiceConfiguration }
	 * 
	 */
	public ServiceConfiguration createServiceConfiguration() {
		return new ServiceConfiguration();
	}

}
