//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.22 at 03:13:00 PM MEZ 
//

package org.adiusframework.service.xml;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.adiusframework.util.GenericToStringExtender;

/**
 * <p>
 * Java class for resourceRequirement complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="resourceRequirement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="capabilityRule" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="types" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="protocols" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resourceRequirement")
public class ResourceRequirement extends GenericToStringExtender implements Serializable {

	private final static long serialVersionUID = 1L;
	@XmlAttribute
	protected String capabilityRule;
	@XmlAttribute
	protected String types;
	@XmlAttribute
	protected String protocols;

	/**
	 * Gets the value of the capabilityRule property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCapabilityRule() {
		return capabilityRule;
	}

	/**
	 * Sets the value of the capabilityRule property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCapabilityRule(String value) {
		this.capabilityRule = value;
	}

	/**
	 * Gets the value of the types property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTypes() {
		return types;
	}

	/**
	 * Sets the value of the types property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTypes(String value) {
		this.types = value;
	}

	/**
	 * Gets the value of the protocols property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProtocols() {
		return protocols;
	}

	/**
	 * Sets the value of the protocols property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setProtocols(String value) {
		this.protocols = value;
	}

}
